all:
	g++ difference.cpp -o ../bin/difference
	g++ dilatation.cpp -o ../bin/dilatation
	g++ eqm.cpp -o ../bin/eqm
	g++ erosion.cpp -o ../bin/erosion
	g++ fermeture.cpp -o ../bin/fermeture
	g++ filtre_flou1.cpp -o ../bin/filtre4voisin
	g++ filtre_flou3.cpp -o ../bin/filtre9voisin
	g++ flouC.cpp -o ../bin/flouC
	g++ gaussian.cpp -o ../bin/gaus
	g++ Gmax.cpp -o ../bin/gmax
	g++ histo.cpp -o ../bin/histo
	g++ hysteresis.cpp -o ../bin/hyst
	g++ inverse.cpp -o ../bin/inverse
	g++ moyenneblur.cpp -o ../bin/moyBlur
	g++ norme_gradient.cpp -lm -o ../bin/Gradient
	g++ ouverture.cpp -o ../bin/ouverture
	g++ profil.cpp -o ../bin/profil
	g++ RGBtoY.cpp -o ../bin/RGBtoY
	g++ RGBtoYCbCr.cpp -o ../bin/RGBtoYCbCr
	g++ test_grey.cpp -o ../bin/s1grey
	g++ test_grey3.cpp -o ../bin/s3grey
	g++ test_couleur.cpp -o ../bin/seuilC
	g++ YCbCr2RBG.cpp -o ../bin/YCbCr2RBG
	g++ YCbCrtoRGREENB.cpp -o ../bin/YCbCrtoRGREENB
	g++ modify.cpp -o ../bin/luminance
	g++ histoC.cpp -o ../bin/histoC
